char *localized_string = (gchar*)resBundle_getLocString(_g_res_bundle_object, "Ivory Coast");
char *localized_string2 = (gchar*)resBundle_getLocString(_g_res_bundle_object, "Programme");
char *localized_string3 = (gchar*)resBundle_getLocString(_g_res_bundle_object, "Sound Out");
char *localized_string4 = (gchar*)resBundle_getLocString(_g_res_bundle_object, "TV Program Locks");
char *localized_string5 = (gchar*)resBundle_getLocString(_g_res_bundle_object, "Service Area Zip Code");
char *localized_string6 = (gchar*)resBundle_getLocString(_g_res_bundle_object, "Time Settings");
char *localized_string7 = (gchar*)resBundle_getLocString(_g_res_bundle_object, "Please enter password.");
char *localized_string8 = (gchar*)resBundle_getLocString(_g_res_bundle_object, "Others");
char *localized_string8 = (gchar*)resBundle_getLocString(_g_res_bundle_object, "Ivory Coast");